language: c++

matrix:
  include:
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-dev
            - libsdl2-mixer-dev
            - libsdl2-ttf-dev
      compiler: g++-7
    - os: linux
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - libstdc++-6-dev
            - libsdl2-dev
            - libsdl2-mixer-dev
            - libsdl2-ttf-dev
      compiler: clang++-5.0
    - os: linux
      env:
        - TARGET=i686-unknown-linux-gnu
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-dev
            - libsdl2-mixer-dev
            - libsdl2-ttf-dev
      compiler: g++-7
    - os: linux
      env:
        - TARGET=i686-unknown-linux-gnu
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - libstdc++-6-dev
            - libsdl2-dev
            - libsdl2-mixer-dev
            - libsdl2-ttf-dev
      compiler: clang++-5.0
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew install gcc; brew link --overwrite gcc && CC=gcc && CXX=g++"
      compiler: g++
    - os: osx
      osx_image: xcode9.3
      compiler: clang++

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf; fi

script:
  - cmake CMakeLists.txt
  - make .

notifications:
  email:
    on_success: never
    on_failure: change